version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql8_container
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - '3366:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
